### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by ashgillman** [olmokramer/atom-autohide-tree-view#17]
Can no longer reproduce.

Initially, I could reproduce the error only if I closed the current tab, reopened then pressed ⌘K right. If I closed the new tab then pressed ⌘K right, no error. If I closed the new and old tab, reopened the old tab and ⌘K right then same error.
After closing all tabs and trying again can no longer reproduce.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.9.5
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.16.5
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Users/Ash/.atom/packages/autohide-tree-view/lib/autohide-tree-view.coffee:119

TypeError: Cannot read property 'classList' of null
  at AutohideTreeView.openEntry (/Users/Ash/.atom/packages/autohide-tree-view/lib/autohide-tree-view.coffee:119:33)
  at atom-workspace.<anonymous> (/Users/Ash/.atom/packages/autohide-tree-view/lib/autohide-tree-view.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -9:50.6.0 gulp-helper:toggle (atom-pane.pane)
     -9:34.6.0 deprecation-cop:view (atom-workspace.workspace.theme-solarized-light-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -9:17 settings-view:check-for-package-updates (atom-workspace.workspace.theme-solarized-light-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -4:02.7.0 command-palette:toggle (atom-pane.pane)
  5x -4:00.1.0 core:move-down (atom-text-editor.editor.mini)
     -3:58.9.0 core:confirm (atom-text-editor.editor.mini)
     -3:58.9.0 settings-view:install-packages-and-themes (atom-pane.pane)
     -3:54.6.0 core:confirm (atom-text-editor.editor.mini)
     -1:04.2.0 gulp-control:toggle (div.settings-view.pane-item)
  2x -0:33.8.0 pane:split-right (atom-pane.pane)
     -0:15.9.0 gulp-control:toggle (atom-pane.pane)
     -0:01.2.0 tree-view:open-selected-entry-right (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ],
    "projectHome": "/Users/Ash/Documents/workspace",
    "disabledPackages": [
      "gulp-helper"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.12.1
autohide-tree-view, v0.16.5
git-log, v0.3.0
gulp-control, v0.3.3
gulp-snippets, v0.6.1
linter, v0.12.1
minimap, v4.7.6
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
I haven't seen this myself... Anyway, I uploaded a new version, 0.17.1, that should be a huge improvement over 0.16.x. Please let me know if you can recreate this issue again. Thanks!

**Comment by ashgillman** [comment]
Not a problem, thanks. I will close this issue and can reopen if necessary later. (y)
