### ISSUE TITLE
Failed to activate the autohide-tree-view package

### ISSUE THREAD

**Issue by chrisvfritz** [olmokramer/atom-autohide-tree-view#29]
I updated the version to 0.22.0 and immediately got this message.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.22.0
### Stack Trace

Failed to activate the autohide-tree-view package

```
At Can't register a command with non-function callback.

Error: Can't register a command with non-function callback.
  at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:44:15)
  at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:39:31)
  at Object.activate (/Users/fritzc/.atom/packages/autohide-tree-view/lib/main.js:34:33)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:312:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
  2x -1:14.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:09.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:56.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:53.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:48 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-afterglow-plus.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "afterglow-plus"
    ],
    "disabledPackages": [
      "livescript-compile"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ]
  },
  "autohide-tree-view": {
    "showDelay": 1,
    "hideDelay": 1,
    "animationSpeed": 2
  }
}
```
### Installed Packages

``` coffee
# User
afterglow-plus, v1.5.0
autohide-tree-view, v0.22.0
color-picker, v2.0.11
file-icon-supplement, v0.8.3
file-icons, v1.5.8
language-cjsx, v0.3.0
language-haml, v0.21.0
language-livescript-edge, v1.0.0
linter, v1.2.4
linter-coffeescript, v1.0.0
linter-js-yaml, v1.1.1
linter-lsc, v2.0.1
minimap, v4.12.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-linter, v1.0.0
minimap-pigments, v0.1.1
pigments, v0.8.4
set-syntax, v0.3.0
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by ProLoser** [comment]
Ditto

**Comment by olmokramer** [comment]
Looks like there's an issue with the update process. Restarting Atom should fix this.

**Comment by olmokramer** [comment]
Is this still an issue?

**Comment by chrisvfritz** [comment]
@olmokramer restarting Atom _did_ fix it and I haven't seen anyone else ditto in a while, so I'll close this.

**Comment by olmokramer** [comment]
Awesome! Now let's hope this doesn't happen with the new version :)

**Comment by OmgImAlexis** [comment]
Just installed the update and I had the same issue. Restarted Atom and it works fine.
