### ISSUE TITLE
Switching to something with touch produces error

### ISSUE THREAD

**Issue by rugk** [olmokramer/atom-autohide-tree-view#47]
[Enter steps to reproduce below:]
1. Current setting: Hover
2. Switch to something with touch. (in this example that's hover + click + touch)

FYI no I have no touch device. 

**Atom Version**: 1.0.7
**System**: ***
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.24.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\%username%\.atom\packages\autohide-tree-view\lib\touch-events.js:46

TypeError: undefined is not a function
  at enable (C:\Users\%username%\.atom\packages\autohide-tree-view\lib\touch-events.js:46:19)
  at C:\Users\%username%\.atom\packages\autohide-tree-view\lib\commands.js:48:55
  at C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:557:16
  at C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:574:20
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:736:29)
  at Config.module.exports.Config.setRawValue (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:551:19)
  at Config.module.exports.Config.set (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:190:28)
  at HTMLSelectElement.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:204:26)
  at HTMLSelectElement.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLSelectElement.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -9:40.6.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -9:23.7.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -9:22.7.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "metrics",
      "autocomplete-php",
      "autocomplete-emojis"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "autohide-tree-view": {
    "showOn": "hover + click + touch",
    "showDelay": 80,
    "hideDelay": 150,
    "animationSpeed": 3,
    "hoverAreaSize": 10,
    "pushEditor": true
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
autohide-tree-view, v0.24.0
color-picker, v2.0.11
editor-stats, v0.17.0
file-icons, v1.6.5
keyboard-localization, v1.4.7
language-autoit, v0.2.1
language-batch, v0.3.3
minimap, v4.12.3
php-analyser, v0.2.0

# Dev
No dev packages
```

**Comment by D-side** [comment]
Yep, there's a ton related issues. I've given my report in #32, since that's the first consequence that has been reported.

**UPD:** Ah yes, you already said that you've checked that =)

**Comment by rugk** [comment]
> UPD: Ah yes, you already said that you've checked that =)

Yes I noticed this error while checking the the error.

**Comment by olmokramer** [comment]
I found the issue. New version will be up in a few minutes.

**Comment by olmokramer** [comment]
New version is up. Please let me know if it works

**Comment by rugk** [comment]
No it doesn't.

**Atom Version**: 1.0.7
**System**: *\* (corrected: Windows 7)
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.24.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\%username%\.atom\packages\autohide-tree-view\lib\touch-events.js:46

TypeError: undefined is not a function
  at enable (C:\Users\%username%\.atom\packages\autohide-tree-view\lib\touch-events.js:46:19)
  at C:\Users\%username%\.atom\packages\autohide-tree-view\lib\commands.js:48:55
  at C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:557:16
  at C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:574:20
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:736:29)
  at Config.module.exports.Config.setRawValue (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:551:19)
  at Config.module.exports.Config.set (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:190:28)
  at HTMLSelectElement.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:204:26)
  at HTMLSelectElement.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLSelectElement.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:56.1.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:37.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

``` json
{
  "core": {
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "metrics",
      "autocomplete-emojis",
      "atom-php-navigation"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "autohide-tree-view": {
    "showDelay": 80,
    "hideDelay": 150,
    "animationSpeed": 3,
    "hoverAreaSize": 10,
    "pushEditor": true
  }
}
```

### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
autocomplete-php, v0.3.7
autohide-tree-view, v0.24.2
color-picker, v2.0.11
editor-stats, v0.17.0
file-icons, v1.6.7
keyboard-localization, v1.4.7
language-autoit, v0.2.1
language-batch, v0.3.3
linter, v1.4.3
minimap, v4.13.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
php-analyser, v0.2.0
pigments, v0.11.0
space-tab, v0.4.2
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by rugk** [comment]
BTW also got this error message in the console:
![autohideerror](https://cloud.githubusercontent.com/assets/11966684/9423120/c521f718-48b6-11e5-99c2-971c0e7bb061.PNG)

**Comment by olmokramer** [comment]
Ok, I think v0.24.3 should fix the issue. Please let me know

**Comment by rugk** [comment]
Indeed it does. :+1: Nice... :smiley:

**Comment by olmokramer** [comment]
Awesome! :smile:
