### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-autohide-tree-view#53]
[Enter steps to reproduce below:]
1. Install Nuclide File tree
2. This happens.

**Atom Version**: 1.0.12-dev-3eddcf4
**System**: "Sabayon Linux
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.24.3
### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of undefined

```
At /home/v3ss/.atom/packages/autohide-tree-view/lib/hover-events.js:35

TypeError: Cannot read property 'appendChild' of undefined
  at enable (/home/v3ss/.atom/packages/autohide-tree-view/lib/hover-events.js:38:32)
  at HTMLBodyElement.onMouseUp (/home/v3ss/.atom/packages/autohide-tree-view/lib/hover-events.js:99:5)

```
### Commands

```
  2x -9:21.6.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
  2x -8:22.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -8:21.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -8:02.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -7:04.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -7:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:54.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.0 nuclide-file-tree:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "whitespace",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "atom-lint",
      "animation-showcase",
      "tree-view-open-files",
      "autocomplete",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "markdown-writer",
      "atom-alignment",
      "autocomplete-atom-api",
      "fancy-input",
      "sublime-tabs",
      "spell-check",
      "tool-bar-main",
      "tool-bar",
      "flex-tool-bar",
      "gutter-shadow",
      "local-history",
      "tab-rename",
      "goto",
      "cursor-blink-interval",
      "auto-reveal-in-sidebar",
      "language-javascript-better",
      "block-cursor",
      "block-travel",
      "emmet",
      "tree-view"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg",
      "./node_modules",
      "node_modules"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "steam-pirate-syntax"
    ]
  },
  "autohide-tree-view": {
    "unfocusTreeViewOnClose": true,
    "showDelay": 5,
    "hideDelay": 5,
    "showOn": "hover"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.7.2
autocomplete-plus-python-jedi, v0.3.6
autohide-tree-view, v0.24.3
browser-plus, v0.0.34
build, v0.46.0
editorconfig, v1.2.0
file-icons, v1.6.9
file-type-icons, v0.7.3
highlight-column, v0.5.0
highlight-selected, v0.10.1
language-nim, v0.2.2
linter, v1.5.2
linter-coffeelint, v1.1.0
linter-csslint, v1.0.5
linter-flake8, v1.6.1
linter-jshint, v1.2.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-selection, v4.3.0
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-hg-repository, v0.0.32
pdf-view, v0.23.0
pigments, v0.15.0
script-runner, v1.8.3
steam-pirate-syntax, v0.3.0
svg-preview, v0.6.1
symbols-tree-view, v0.10.0
tabs-to-spaces, v0.11.1
vim-mode, v0.60.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
autohide-tree-view currently doesn't support nuclide-file-tree, because nuclide-file-tree disables the original tree-view package. I'll add it to the todo list, but I can't promise to do it very soon.

**Comment by v3ss0n** [comment]
Thanks olmo! No worries , i disabled nuclided file-tree currently too :D .
