### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by modulexcite** [olmokramer/atom-autohide-tree-view#60]
[Enter steps to reproduce below:]
1. On Atom Startup, I see this error in the dev toolbar.
2. Also the tree view doesn't open until i have an actual file open.

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.25.1
### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /C:/Users/tom.green/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:118

TypeError: Cannot read property 'style' of undefined
    at updateTreeView (C:/Users/tom.green/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:91:8)
    at enableAutohide (C:/Users/tom.green/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:27:3)
    at start (C:/Users/tom.green/.atom/packages/autohide-tree-view/lib/main.js:71:3)
    at updateActivationState (C:/Users/tom.green/.atom/packages/autohide-tree-view/lib/main.js:47:35)
    at C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:132:16
    at Emitter.module.exports.Emitter.emit (C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:375:27)
    at C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:359:28
    at Emitter.module.exports.Emitter.emit (C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.addItem (C:\Users\tom.green\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:339:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "E:\\TGreen\\DocStore\\Atom",
    "disabledPackages": [
      "file-type-icons",
      "nuclide-file-tree",
      "nuclide-tabs",
      "tree-view-open-files",
      "enhanced-package-list",
      "terminal-plus",
      "markdown-scroll-sync",
      "sync-settings",
      "package-list"
    ]
  },
  "autohide-tree-view": {
    "pushEditor": true,
    "showOn": "click"
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-html-preview, v0.1.13
atom-snippets, v0.1.1
atom-ternjs, v0.8.4
atom-typescript, v7.8.0
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
autocomplete-python, v0.10.3
autohide-tree-view, v0.25.1
color-picker, v2.0.13
color-tabs, v0.1.8
column-select, v0.2.0
command-toolbar, v1.0.12
css-snippets, v0.9.0
docblockr, v0.7.3
editor-stats, v0.17.0
emmet, v2.3.14
file-icons, v1.6.11
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jsformat, v0.9.0
language-log, v1.1.0
language-powershell, v2.1.0
linter, v1.10.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-scss-lint, v2.4.0
local-history, v3.2.3
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
nodejs-snippets, v1.0.3
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-find-references, v0.0.32
package-cop, v0.2.10
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
regex-railroad-diagram, v0.10.4
save-session, v0.15.7
Sublime-Style-Column-Selection, v1.3.0
symbol-gen, v1.0.0
symbols-tree-view, v0.10.1
tabs-to-spaces, v0.11.1
tree-view-breadcrumb, v0.8.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by spencerthayer** [comment]
I am getting this error.

**Comment by tarkanlar** [comment]
Same here +1

**Comment by danielbayley** [comment]
I just got this too 😞

**Comment by muzzotech** [comment]
I should have read this before installing it, but yeah, same error
