### ISSUE TITLE
Error: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by Yaco** [olmokramer/atom-autohide-tree-view#78]
The package s not working for me in beta version:

**Atom Version**: 1.12.0-beta0
**Electron Version**: 1.3.6
**System**: "Manjaro Linux"
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.25.1
### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at showTreeView (/home/yaco/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:111:17)
    at toggleTreeView (/home/yaco/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:145:42)
    at atom-workspace.treeViewToggle (/home/yaco/.atom/packages/autohide-tree-view/lib/commands.js:29:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:59)
```
### Commands

```
  2x -0:28.2.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:14.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:00.3.0 tree-view:toggle (button.btn.icon.enablement.icon-playback-pause)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "typewriter-sounds",
      "keyboard-scroll",
      "node_modules"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "bookmarks"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "no-caffeine-syntax"
    ]
  },
  "autohide-tree-view": {
    "pushEditor": true
  }
}
```

**Comment by keskiju** [comment]
Does not work in the latest Atom release either (Atom v1.11.1).

**Comment by andyjeffries** [comment]
I don't know how you guys are getting the crash, but for me:

Press the keyboard shortcut mapped to tree-view:reveal-active-file when you have autohide-tree-view installed and it crashes with this error (subsequent key presses work).

**Comment by andyjeffries** [comment]
@olmokramer I'm still getting this crash, pinging you to see if you're aware of it/working on it?

**Comment by warent** [comment]
Happens for me usually when I try to close a tab with the middle mouse button.

**Comment by vlork** [comment]
+1 when right-click and select "Reveal in tree view" and tree view is hidden. When tree view is visible it works. Atom 1.14.1 on Linux.

**Comment by ethernal** [comment]
This is still valid issue in Atom 1.15 (Windows OS) happens only when trying to toggle tree view while it's hidden. Can it be fixed? Is this package maintained?

**Comment by itotallyrock** [comment]
I had this issue with one of my packages and the fix was in the `onDidDestroy` method.  Not too sure if this specifically relates to this repo but I found this issue when trying to resolve my own issue.  So hopefully if any does find this, this can give some insight to the source of the issue.
