### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by andyjeffries** [olmokramer/atom-autohide-tree-view#79]
[Enter steps to reproduce below:]
1. Press the keyboard shortcut mapped to `tree-view:reveal-active-file` when you have autohide-tree-view installed
2. Crashes

**Atom Version**: 1.11.1
**Autohide-Tree-View Version**: 0.25.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.25.1
### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at showTreeView (/Users/andy/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:111:17)
    at atom-workspace.treeViewRevealActiveFile (/Users/andy/.atom/packages/autohide-tree-view/lib/commands.js:34:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1127:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
     -0:20.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -0:05.8.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
  2x -0:04.0 pane:show-item-1 (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -0:03.3.0 pane:show-item-2 (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -0:00.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-toml",
      "language-c",
      "autocomplete",
      "archive-view",
      "open-on-github",
      "autosave",
      "ruby-string-interpolation",
      "deprecation-cop",
      "atom-duplicate",
      "markdown-preview",
      "markdown-format",
      "language-gfm",
      "activate-power-mode"
    ],
    "ignoredNames": [
      "*.pdf",
      "*.paw",
      "*.xls",
      "*.xlsx",
      "*.webm",
      "*.mp4",
      "*.ogv",
      "*.flv",
      "*.doc",
      "*.docx",
      "*.mp3",
      "*.ogg",
      "*.wav",
      "*.pyc",
      "*.pyo",
      "*.exe",
      "*.dll",
      "*.obj",
      "*.gem",
      "*.o",
      "*.a",
      "*.swf",
      "*.lib",
      "*.so",
      "*.dylib",
      "*.ncb",
      "*.sdf",
      "*.suo",
      "*.pdb",
      "*.idb",
      ".DS_Store",
      ".keep",
      "*.class",
      "*.psd",
      "*.db",
      "*.scssc",
      "*.log",
      "*.gz",
      "*.tgz",
      "Godeps"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-alignment"
    ],
    "projectHome": "/Users/andy",
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "autohide-tree-view": {
    "animationSpeed": 3,
    "hoverAreaSize": 15,
    "pushEditor": true
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.4 (inactive)
ask-stack, v2.2.0 (inactive)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.13 (inactive)
atom-dark-fusion-syntax, v1.2.4 (inactive)
atom-jasmine, v0.8.1 (active)
atom-pair, v2.0.10 (active)
autohide-tree-view, v0.25.1 (active)
change-case, v0.6.3 (active)
color-picker, v2.2.2 (active)
copy-as-rtf, v0.9.3 (inactive)
delete-lines, v0.4.17 (inactive)
duotone-light-syntax, v1.0.0 (inactive)
duplicate-line-or-selection, v0.8.0 (inactive)
environment, v1.3.1 (active)
export-html, v3.0.0 (inactive)
expose, v0.12.1 (inactive)
file-icons, v1.7.22 (active)
filesize, v1.0.0 (active)
git-blame, v0.4.11 (inactive)
git-control, v0.8.2 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (active)
go-get, v2.1.1 (active)
gofmt, v1.2.0 (active)
gorename, v1.1.0 (active)
goto, v1.7.1 (inactive)
jumpy, v3.1.3 (inactive)
language-make, v0.22.2 (active)
language-markdown, v0.16.3 (active)
language-puppet, v0.21.0 (active)
linter, v1.11.18 (active)
linter-golint, v0.3.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-jshint, v3.0.1 (active)
linter-ruby, v1.2.2 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.1 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
nucleus-dark-ui, v0.10.11 (inactive)
pain-split, v1.4.0 (active)
pdf-view, v0.50.0 (active)
rails-latest-migration, v1.1.6 (inactive)
rails-snippets, v2.8.0 (inactive)
regex-railroad-diagram, v0.16.0 (active)
rspec, v0.3.2 (inactive)
ruby-syntax-replacer, v0.5.1 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
tidy-markdown, v3.0.1 (active)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (active)
tool-bar-almighty, v0.8.1 (active)
tree-ignore, v0.6.2 (active)
view-tail-large-files, v0.2.1 (active)
wordcount, v2.7.0 (active)
yeti-syntax, v0.1.2 (inactive)
yeti-ui, v0.1.6 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by andyjeffries** [comment]
Duplicate of #78

**Comment by wayneseymour** [comment]
bump
