### ISSUE TITLE
Uncaught TypeError: Failed to create DOMEventListener: parameter 1 is not of type EventTarget

### ISSUE THREAD

**Issue by matteorizzuto** [olmokramer/atom-autohide-tree-view#85]
I have been getting this error for a while now, it shows up when I start Zen mode ([https://atom.io/packages/zen](https://atom.io/packages/zen)) in full screen. I looked for a pattern in its occurence, but so far it seems to be random. 

Below are my system specs.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package 0.25.1

### Stack Trace

Uncaught TypeError: Failed to create DOMEventListener: parameter 1 is not of type EventTarget

```
At /Users/matteo/.atom/packages/autohide-tree-view/lib/utils.js:9

TypeError: Failed to create DOMEventListener: parameter 1 is not of type EventTarget
    at domListener (/packages/autohide-tree-view/lib/utils.js:9:11)
    at disableHoverEventsUntilBlur (/packages/autohide-tree-view/lib/hover-events.js:53:3)
    at showTreeView (/packages/autohide-tree-view/lib/autohide-tree-view.js:111:21)
    at toggleTreeView (/packages/autohide-tree-view/lib/autohide-tree-view.js:145:42)
    at /packages/autohide-tree-view/lib/commands.js:29:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at Object.toggle (/packages/zen/lib/zen.coffee:155:23)
    at /packages/zen/lib/zen.coffee:53:59)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:05.4.0 zen:toggle (input.hidden-input)
     -0:05.4.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-atom-material-syntax-light.theme-atom-material-ui.has-custom-icons)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-clock 0.1.6 
atom-itunes 0.5.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
aurora-theme 1.2.2 
autocomplete-bibtex 0.7.0 
autohide-tree-view 0.25.1 
busy-signal 1.3.0 
color-picker 2.2.5 
dictionary 0.5.0 
duotone-blue-dark-syntax 1.4.0 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.3 
git-hide 1.0.0 
git-plus 7.4.0 
git-time-machine 1.5.9 
hey-pane 0.2.2 
highlight-selected 0.13.1 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-latex 1.0.0 
latex 0.43.0 
latex-friend 0.0.11 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
linter 2.1.2 
linter-chktex 1.3.0 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
minimap 4.27.1 
minimap-autohider 1.4.0 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
nord-atom-syntax 0.8.0 
nord-atom-ui 0.11.0 
paper-flat-ui 1.3.6 
pdf-view 0.57.0 
pigments 0.39.1 
preview-inline 1.4.5 
project-manager 3.3.4 
script 3.14.1 
seti-classic-syntax 0.5.0 
skim-displayline 0.0.1 
solarized-seti-ui 0.8.6 
theme-switcher 1.1.0 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by nelson6e65** [comment]
I'm having this issue too when I click on editor context-menu "Reveal in Tree View".
